data:
  train_files: BLINK-Benchmark/BLINK
  val_files: BLINK-Benchmark/BLINK
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 2048
  max_response_length: 2048
  rollout_batch_size: 4 # 512
  val_batch_size: -1 # 1024
  format_prompt: ./examples/format_prompt/tools_thinker_format.jinja
  override_chat_template: null
  shuffle: true
  seed: 1 # 42
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: false
  subtasks: ["Counting"]  # ["Counting","Art_Style"] # subtasks list or null
  dataset_prefix: /home/stud/wxie # Dataset root path # BLINK:/home/stud/wxie # SAT:/nfs/data8/liao/wxie/SAT/
  tools_config: ./examples/tools_config/tools_configuration_file.yaml

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 2 # 128
    micro_batch_size_per_device_for_update: 2 # 4
    micro_batch_size_per_device_for_experience: 4 # 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16 # add flash-attn2 (Ampere GPU) 
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5 # 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.5 # 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
      torch_dtype: bf16 # add flash-attn2 (Ampere GPU) 
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/tool_reward.py:compute_score
    reward_function_kwargs:
      format_weight: 0.3
      usage_weight: 0.5
      execution_weight: 0.2
    num_gpus: 0
    num_cpus: 1

trainer:
  total_epochs: 1 # 15
  max_steps: null
  project_name: Debug # easyr1
  experiment_name: qwen2_5_3b_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: -1  # -1 to disable default:5
  val_before_train: false # true
  val_only: false
  val_generations_to_log: 3
  save_freq: -1  # -1 to disable
  save_limit: 3  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null
